# A Makefile for building this project and linking it with third-party software.
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# The roots of Google Test and nauty.
GTEST_DIR = gtest-1.7.0
NAUTY_DIR = nauty

# Where to find user code.
GRAPH_UTILS_DIR = graph_utils
NAUTY_UTILS_DIR = nauty_utils
MAIN_DIR = main

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -isystem $(GTEST_DIR)/include -isystem ./

# Flags passed to the C++ compiler.
CXXFLAGS += -std=c++0x -g -Wall -Wextra -Wno-write-strings -Wno-unused-parameter -pthread -O3

# All tests produced by this Makefile.
TESTS = graph_test.exe graph_utilities_test.exe girth_5_graph_test.exe \
        graph_generator_test.exe canonical_graph_generator_test.exe \
        nauty_wrapper_test.exe

# All programs produced by this Makefile.
MAINS = diamond_free_graphs.exe canonical_diamond_free_graphs.exe \
        girth_5_graphs.exe canonical_girth_n_graphs.exe \
        callgeng_generic_girth.exe callgeng_generic_dfg.exe

# All Google Test headers.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

# House-keeping build targets.

all : $(TESTS) $(MAINS)

clean :
	rm -f $(TESTS) $(MAINS) gtest.a gtest_main.a *.o

# Builds gtest.a and gtest_main.a.

GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)

gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS) $@ $^

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^

################################################################################ 
#                              BUILDING USER CODE                              #
################################################################################

# graph_utils
graph.o : $(GRAPH_UTILS_DIR)/graph.cc $(GRAPH_UTILS_DIR)/graph.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/graph.cc

graph_test.o : $(GRAPH_UTILS_DIR)/graph_test.cc \
               $(GRAPH_UTILS_DIR)/graph.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/graph_test.cc

graph_test.exe : graph.o graph_test.o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@


graph_utilities.o : $(GRAPH_UTILS_DIR)/graph_utilities.cc \
                    $(GRAPH_UTILS_DIR)/graph_utilities.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/graph_utilities.cc

graph_utilities_test.o : $(GRAPH_UTILS_DIR)/graph_utilities_test.cc \
                         $(GRAPH_UTILS_DIR)/graph_utilities.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/graph_utilities_test.cc

graph_utilities_test.exe : graph_utilities.o graph_utilities_test.o graph_generator.o gtest_main.a \
                           graph.o nauty_wrapper.o $(NAUTY_DIR)/nauty.o $(NAUTY_DIR)/nautil.o $(NAUTY_DIR)/naugraph.o \
                           $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

girth_5_graph.o : $(GRAPH_UTILS_DIR)/girth_5_graph.cc $(GRAPH_UTILS_DIR)/girth_5_graph.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/girth_5_graph.cc

girth_5_graph_test.o : $(GRAPH_UTILS_DIR)/girth_5_graph_test.cc \
                       $(GRAPH_UTILS_DIR)/girth_5_graph.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/girth_5_graph_test.cc

girth_5_graph_test.exe : girth_5_graph.o girth_5_graph_test.o graph_utilities.o gtest_main.a graph.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@


graph_generator.o : $(GRAPH_UTILS_DIR)/graph_generator.cc \
                    $(GRAPH_UTILS_DIR)/graph_generator.h \
                    $(NAUTY_UTILS_DIR)/nauty_wrapper.h \
                    $(GRAPH_UTILS_DIR)/graph_utilities.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/graph_generator.cc

graph_generator_test.o : $(GRAPH_UTILS_DIR)/graph_generator_test.cc \
                         $(GRAPH_UTILS_DIR)/graph_generator.h \
                         $(GRAPH_UTILS_DIR)/graph_utilities.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/graph_generator_test.cc

graph_generator_test.exe : graph_generator.o graph_generator_test.o \
                           $(NAUTY_DIR)/nauty.o $(NAUTY_DIR)/nautil.o $(NAUTY_DIR)/naugraph.o \
                           $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o \
                           graph.o graph_utilities.o nauty_wrapper.o \
                           gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

canonical_graph_generator.o : $(GRAPH_UTILS_DIR)/canonical_graph_generator.cc \
                              $(GRAPH_UTILS_DIR)/canonical_graph_generator.h \
                              $(NAUTY_UTILS_DIR)/nauty_wrapper.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/canonical_graph_generator.cc

canonical_graph_generator_test.o : $(GRAPH_UTILS_DIR)/canonical_graph_generator_test.cc \
                                   $(GRAPH_UTILS_DIR)/canonical_graph_generator.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(GRAPH_UTILS_DIR)/canonical_graph_generator_test.cc

canonical_graph_generator_test.exe : canonical_graph_generator_test.o canonical_graph_generator.o \
                                     graph.o graph_utilities.o nauty_wrapper.o $(NAUTY_DIR)/nauty.o \
                                     $(NAUTY_DIR)/nautil.o $(NAUTY_DIR)/naugraph.o \
                                     $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o \
                                     gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

# core nauty
$(NAUTY_DIR)/nauty.o : $(NAUTY_DIR)/nauty.c $(NAUTY_DIR)/nauty.h
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(NAUTY_DIR)/nauty.c

$(NAUTY_DIR)/nautil.o : $(NAUTY_DIR)/nautil.c
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(NAUTY_DIR)/nautil.c

$(NAUTY_DIR)/naugraph.o : $(NAUTY_DIR)/naugraph.c
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(NAUTY_DIR)/naugraph.c

$(NAUTY_DIR)/schreier.o : $(NAUTY_DIR)/schreier.c
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(NAUTY_DIR)/schreier.c

$(NAUTY_DIR)/naurng.o : $(NAUTY_DIR)/naurng.c
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(NAUTY_DIR)/naurng.c

# nauty_utils
nauty_wrapper.o : $(NAUTY_UTILS_DIR)/nauty_wrapper.cc $(NAUTY_UTILS_DIR)/nauty_wrapper.h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(NAUTY_UTILS_DIR)/nauty_wrapper.cc

nauty_wrapper_test.o : $(NAUTY_UTILS_DIR)/nauty_wrapper_test.cc \
                       $(NAUTY_UTILS_DIR)/nauty_wrapper.h \
                       $(GRAPH_UTILS_DIR)/graph.h $(GTEST_HEADERS) 
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(NAUTY_UTILS_DIR)/nauty_wrapper_test.cc

nauty_wrapper_test.exe : graph.o nauty_wrapper.o nauty_wrapper_test.o gtest_main.a \
                         $(NAUTY_DIR)/nauty.o $(NAUTY_DIR)/nautil.o $(NAUTY_DIR)/naugraph.o \
                         $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

# main programs
diamond_free_graphs.o : $(MAIN_DIR)/diamond_free_graphs.cc
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(MAIN_DIR)/diamond_free_graphs.cc

diamond_free_graphs.exe : diamond_free_graphs.o graph_utilities.o graph_generator.o graph.o nauty_wrapper.o \
                          $(NAUTY_DIR)/nauty.o $(NAUTY_DIR)/nautil.o $(NAUTY_DIR)/naugraph.o \
                          $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

canonical_diamond_free_graphs.o : $(MAIN_DIR)/canonical_diamond_free_graphs.cc
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(MAIN_DIR)/canonical_diamond_free_graphs.cc

canonical_diamond_free_graphs.exe : canonical_diamond_free_graphs.o canonical_graph_generator.o graph.o \
                                    graph_utilities.o nauty_wrapper.o $(NAUTY_DIR)/nauty.o $(NAUTY_DIR)/nautil.o \
                                    $(NAUTY_DIR)/naugraph.o $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

girth_5_graphs.o : $(MAIN_DIR)/girth_5_graphs.cc
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(MAIN_DIR)/girth_5_graphs.cc

girth_5_graphs.exe : girth_5_graphs.o girth_5_graph.o graph_utilities.o graph_generator.o graph.o nauty_wrapper.o \
                          $(NAUTY_DIR)/nauty.o $(NAUTY_DIR)/nautil.o $(NAUTY_DIR)/naugraph.o \
                          $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

canonical_girth_n_graphs.o : $(MAIN_DIR)/canonical_girth_n_graphs.cc
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(MAIN_DIR)/canonical_girth_n_graphs.cc

canonical_girth_n_graphs.exe : canonical_girth_n_graphs.o girth_5_graph.o canonical_graph_generator.o graph.o \
                                    graph_utilities.o nauty_wrapper.o $(NAUTY_DIR)/nauty.o $(NAUTY_DIR)/nautil.o \
                                    $(NAUTY_DIR)/naugraph.o $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

callgeng_generic_girth.exe : $(NAUTY_DIR)/geng.c $(MAIN_DIR)/callgeng_generic_girth.cc girth_5_graph.o graph_utilities.o graph.o \
                             $(NAUTY_DIR)/gtools.o $(NAUTY_DIR)/nauty1.o $(NAUTY_DIR)/nautil1.o $(NAUTY_DIR)/naugraph1.o \
                             $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o 
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -DMAXN=32 -DOUTPROC=myoutproc -DGENG_MAIN=geng_main -DPRUNE=geng_prune -lpthread $^ -o $@

callgeng_generic_dfg.exe : $(NAUTY_DIR)/geng.c $(MAIN_DIR)/callgeng_generic_dfg.cc girth_5_graph.o graph_utilities.o graph.o \
                             $(NAUTY_DIR)/gtools.o $(NAUTY_DIR)/nauty1.o $(NAUTY_DIR)/nautil1.o $(NAUTY_DIR)/naugraph1.o \
                             $(NAUTY_DIR)/schreier.o $(NAUTY_DIR)/naurng.o 
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -DMAXN=32 -DOUTPROC=myoutproc -DGENG_MAIN=geng_main -DPRUNE=geng_prune -lpthread $^ -o $@

